/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zsd_win32_utils_OSNative */

#ifndef _Included_org_zsd_win32_utils_OSNative
#define _Included_org_zsd_win32_utils_OSNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    PostQuitMessage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_PostQuitMessage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    char_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_char_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    wchar_t_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_wchar_1t_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    short_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_short_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    int_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_int_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    long_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_long_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    handle_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_handle_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    AllocateBuffer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_AllocateBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    AllocateMore
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_utils_OSNative_AllocateMore
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    FreeBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_FreeBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    setByteArray
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_setByteArray
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getByteArray
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zsd_win32_utils_OSNative_getByteArray__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getByteArray
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zsd_win32_utils_OSNative_getByteArray__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    setShortArray
 * Signature: (I[S)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_setShortArray
  (JNIEnv *, jclass, jint, jshortArray);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getShortArray
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_org_zsd_win32_utils_OSNative_getShortArray__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getShortArray
 * Signature: (II)[S
 */
JNIEXPORT jshortArray JNICALL Java_org_zsd_win32_utils_OSNative_getShortArray__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    setIntArray
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_setIntArray
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getIntArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_zsd_win32_utils_OSNative_getIntArray__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getIntArray
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_org_zsd_win32_utils_OSNative_getIntArray__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    setLongArray
 * Signature: (I[J)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_setLongArray
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getLongArray
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_zsd_win32_utils_OSNative_getLongArray__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getLongArray
 * Signature: (II)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_zsd_win32_utils_OSNative_getLongArray__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getDoubleNullTerminatedByteArray
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zsd_win32_utils_OSNative_getDoubleNullTerminatedByteArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getNullTerminatedCString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zsd_win32_utils_OSNative_getNullTerminatedCString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getNullTerminatedCWideString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zsd_win32_utils_OSNative_getNullTerminatedCWideString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getDoubleNullTerminatedCString
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_zsd_win32_utils_OSNative_getDoubleNullTerminatedCString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getDoubleNullTerminatedCWideString
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_zsd_win32_utils_OSNative_getDoubleNullTerminatedCWideString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    getCWideString
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zsd_win32_utils_OSNative_getCWideString
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    setCString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_setCString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_zsd_win32_utils_OSNative
 * Method:    setCWideString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zsd_win32_utils_OSNative_setCWideString
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif