/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zsd_win32_pcsc_PCSC */

#ifndef _Included_org_zsd_win32_pcsc_PCSC
#define _Included_org_zsd_win32_pcsc_PCSC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCARD_READERSTATE_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCARD_1READERSTATE_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCARD_IO_REQUEST_sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCARD_1IO_1REQUEST_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardEstablishContext
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardEstablishContext
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardReleaseContext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardReleaseContext
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardIsValidContext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardIsValidContext
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardListReaders
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardListReaders
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardFreeMemory
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardFreeMemory
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardGetStatusChange
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardGetStatusChange
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardCancel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardCancel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardConnect
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardConnect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardDisconnect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardDisconnect
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardReconnect
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardReconnect
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardBeginTransaction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardBeginTransaction
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardEndTransaction
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardEndTransaction
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardGetAttrib
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardGetAttrib
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardStatus
 * Signature: (IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardStatus
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_zsd_win32_pcsc_PCSC
 * Method:    SCardTransmit
 * Signature: (IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_zsd_win32_pcsc_PCSC_SCardTransmit
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif